version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Docker/Dockerfile
    container_name: pet-clicker-api
    tty: true
    depends_on:
      - db
      - redis
    environment:
      APP_ENV: "${APP_ENV:-local}"
      APP_KEY: "${APP_KEY:-base64:Pzpr6eyHrOV5Q9sBNa7U54P05aSN36y5IdoalOC3Ek0=}"
      #DATABASE_URL: ${DATABASE_URL:-postgresql://devuser:devsecret@127.0.0.1:5432/devdb}
    working_dir: /var/www
    networks:
        - backend
    volumes:
      - ./:/var/www
      - ./Docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini

  webserver:
    image: nginx:stable
    container_name: nginx
    restart: unless-stopped
    ports:
      - "${APP_PORT:-8084}:80"
    depends_on:
      - app
    networks:
      - backend
    volumes:
      - ./:/var/www
      - ./Docker/app.conf:/etc/nginx/conf.d/default.conf
    links:
      - app
  redis:
    container_name: pet-clicker-redis
    image: redis:latest
    networks:
        - backend
    volumes:
        - redisdata:/data
    ports:
        - "${DOCKER_REDIS_PORT:-6379}:6379"

  db:
    image: postgres:12
    container_name: pet-clicker-db
    restart: unless-stopped
    networks:
        - backend
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: devsecret
      POSTGRES_USER: devuser
      POSTGRES_DB: pet_clicker
    ports:
      - "${DOCKER_DB_PORT:-5433}:5432"

  # dbtest:
  #   image: postgres:12
  #   container_name: dbtest
  #   restart: unless-stopped
  #   volumes:
  #     - db_data_test:/var/lib/postgresql/data
  #   environment:
  #     POSTGRES_PASSWORD: testsecret
  #     POSTGRES_USER: testuser
  #     POSTGRES_DB: testdb
  #   ports:
  #     - "54321:5432"
networks:
  backend:
    driver: bridge
volumes:
  db_data:
    driver: local
  # db_data_test:
  #   driver: local
  redisdata:
    driver: local